version: "3"
services:
  support:
    image: hpccsystems/hpcc:7-rc
    networks:
      - ovnet
  esp:
    image: hpccsystems/hpcc:7-rc
    ports:
      - "8010:8010"
    networks:
      - ovnet
  admin:
    image: hpccsystems/hpcc-m:7-admin
    ports:
      - "8015:8015"
    # privileged: true
    # tty: true
    environment:
     #- HOST_IP=172.17.0.1
      - TOPOLOGY=default
    networks:
      - ovnet
  thor-mythor:
    image: hpccsystems/hpcc:7-rc
    deploy:
      replicas: 2
    networks:
      - ovnet
  roxie-myroxie:
    image: hpccsystems/hpcc:7-rc
    deploy:
      replicas: 2
    networks:
      - ovnet
networks:
  ovnet:
